### ISSUE TITLE
Brackets instead of parents for programmatic property picking

### ISSUE THREAD

**Issue by trusktr** [rtm/js-pick-notation#1]
Why not 

``` js
o.{[name1], [name2]}
```

instead of 

``` js
o.{(name1), (name2)}
```

so that I follows the same pattern of square brackets from

``` js
{[name1]: o[name1], [name2]: o[name2]}
```

?  That seems to be more intuitive.

**Comment by rtm** [comment]
Closing this issue as it relates to an earlier, obsolete version of the proposal.
