### ISSUE TITLE
Guarded pick notation

### ISSUE THREAD

**Issue by raulsebastianmihaila** [rtm/js-pick-notation#2]
How about writing o.!a for guarded pick instead of o.?a  ?
It would be similar to the mandatory properties notation.
? makes me think of optional stuff.

**Comment by peisenmann** [comment]
I've heard this called the "Null Safe Deferencing" operator before. Groovy, for example, uses the `o?.a`. Using the ! makes me think of logical not, so I don't see the switch from ? to ! to be a win. Either a question mark and dot or a symbol that isn't used elsewhere makes the most sense imho.

**Comment by raulsebastianmihaila** [comment]
Consistency with `o.{a, b!} `. Or this could be written as `o.{a, b?} ` instead.

**Comment by rtm** [comment]
Closing this issue as it relates to an earlier, obsolete version of the proposal.
